[build]
  base = "Client"
  publish = "dist"
  command = "npm run build"

[dev]
  framework = "vite"

[[redirects]]
  from = "/*"
  to = "https://elasticsearchproject-server-production.up.railway.app/api/:splat"
  status = 200
  force = true
